services:
  # Spring Boot API service
  users-api:
    build: . # builds the image from the Dockerfile
    container_name: users-api
    restart: always
    ports:
      - "8001:8001" # host:container port mapping
    depends_on:
      mysql-db: # ensures database starts before the API
        condition: service_healthy
    environment:
      # environment variables used by Spring Boot to connect to the shared database
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/sd3db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - cis-network

  # Shared Database service
  mysql-db:
    image: mysql:8.0 # official MySQL image
    container_name: mysql-db
    restart: always # automatically restarts if the container stops
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sd3db # creates the database automatically
    ports:
      - "3306:3306" # default MySQL port
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cis-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

# Shared external Docker network
# Must be created manually before running containers:
# docker network create cis-network
networks:
  cis-network:
    external: true