services:
  # Spring Boot API service
  users-api:
    build: . # builds the image from the Dockerfile
    container_name: users-api
    restart: always
    ports:
      - "8001:8001" # host:container port mapping
    depends_on:
      - mysql # ensures database starts before the API
    environment:
      # environment variables used by Spring Boot to connect to the database
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sd3db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  # Database service
  mysql:
    image: mysql:8.0 # official MySQL image
    container_name: users-mysql
    restart: always # automatically restarts if the container stops
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sd3db # creates the database automatically
    ports:
      - "3306:3306" # default MySQL port
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
