server.port=8001

# "mysql" é o nome do serviço no docker-compose (hostname interno)
spring.datasource.url=jdbc:mysql://mysql:3306/sd3db
spring.datasource.username=root
spring.datasource.password=root

# TODO: evoluir o setup do banco nas próximas sprints
